name: Auto Translate JSON

on:
  push:
    paths:
      - 'ru.json'
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run translation script
        run: python enhanced_translator.py

      - name: Commit and push translations
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add en.json zh.json
          git diff --cached --quiet || git commit -m "🤖 Auto-update translations from ru.json"
          git push
